spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      resourceserver:
        # jwt:
          # issuer-uri: http://localhost:9999/auth/realms/one
        opaque-token:
          introspection-uri: http://localhost:9999/auth/realms/one/protocol/openid-connect/token/introspect
          client-id: app
          client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a
#  datasource:
#    url: jdbc:mysql://localhost:3306/securitiy-test-pluralsight?serverTimezone=UTC
#    username: root
#    password: 12345
#    driver-class-name: com.mysql.cj.jdbc.Driver




server:
  port: 8079
