spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/auth/realms/one
#  datasource:
#    url: jdbc:mysql://localhost:3306/securitiy-test-pluralsight?serverTimezone=UTC
#    username: root
#    password: 12345
#    driver-class-name: com.mysql.cj.jdbc.Driver




server:
  port: 8079
